from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence


FREEPIK_MODEL_ID = "Freepik/nsfw_image_detector"
FREEPIK_MODEL_REVISION = "800d7f87543397a56396f4803255028ebae5a189"
FREEPIK_MODEL_LICENSE = "MIT"
CLIP_MODEL_ID = "openai/clip-vit-base-patch32"
CLIP_MODEL_REVISION = "c7244be81152024ce0e99ac8d2e373a8953d9f9a"
CLIP_MODEL_LICENSE = "MIT"

CANDIDATE_LABELS = (
    "verified_art_culture_or_education",
    "non_explicit_intimacy",
    "explicit_adult_sexual_content",
    "safe_or_other",
    "uncertain",
)

# Equal prompt counts avoid giving any class extra mass solely because it has
# more prompt variants. These strings are fixed development configuration, not
# generated by an LLM.
PROMPT_GROUPS: Mapping[str, tuple[str, ...]] = {
    "verified_art_culture_or_education": (
        "a museum artwork or fine-art painting",
        "a classical nude painting presented as art",
        "a public monument or classical sculpture",
        "an educational anatomy, medical, or health illustration",
    ),
    "non_explicit_intimacy": (
        "a non-explicit intimate scene with clothed adults",
        "adults in underwear in a romantic scene without visible nudity",
        "a suggestive film scene without visible private parts",
        "a romantic bedroom scene without explicit sexual activity",
    ),
    "explicit_adult_sexual_content": (
        "adult explicit sexual activity",
        "adult nudity with visible private parts",
        "pornographic adult visual content",
        "an explicit adult sex scene",
    ),
    "safe_or_other": (
        "an ordinary safe everyday photograph",
        "a landscape, building, animal, or object photograph",
        "a fully clothed person in a nonsexual scene",
        "a fully blurred image with no explicit detail visible",
    ),
}


@dataclass(frozen=True)
class VisualEvidenceV7Config:
    max_frames: int = 8
    art_minimum: float = 0.34
    art_margin_over_explicit: float = 0.06
    explicit_clip_minimum: float = 0.27
    explicit_sexual_risk_minimum: float = 0.78
    explicit_high_override: float = 0.82
    explicit_medium_override: float = 0.80
    explicit_medium_override_risk: float = 0.94
    intimacy_minimum: float = 0.32
    intimacy_margin: float = 0.03
    intimacy_medium_maximum: float = 0.79
    safe_minimum: float = 0.40
    # The four CLIP group scores are relative and sum to one. This is a
    # conservative separation floor, not a claim that CLIP is calibrated.
    decision_minimum: float = 0.30
    frame_consensus_minimum: float = 0.60


def model_licence_manifest() -> dict[str, Any]:
    return {
        "models": [
            {
                "model_id": FREEPIK_MODEL_ID,
                "revision": FREEPIK_MODEL_REVISION,
                "declared_license": FREEPIK_MODEL_LICENSE,
                "model_card": "https://huggingface.co/Freepik/nsfw_image_detector",
                "access_gated": False,
                "permission_request_required": False,
                "weights_format_required": "safetensors",
                "training_summary": "100,000 synthetically labelled images",
                "training_data_provenance_complete": False,
            },
            {
                "model_id": CLIP_MODEL_ID,
                "revision": CLIP_MODEL_REVISION,
                "declared_license": CLIP_MODEL_LICENSE,
                "model_card": "https://huggingface.co/openai/clip-vit-base-patch32",
                "source_repository": "https://github.com/openai/CLIP",
                "access_gated": False,
                "permission_request_required": False,
                "weights_format_required": "safetensors",
                "training_data_provenance_complete": False,
                "deployment_requires_task_specific_validation": True,
            },
        ],
        "all_declared_licenses_permissive": True,
        "permission_request_required": False,
        "training_data_imported": False,
        "training_data_provenance_complete": False,
        "legal_approval_claimed": False,
        "development_use_only": True,
        "production_eligible": False,
    }


def _mean(values: Iterable[float]) -> float:
    items = list(values)
    return sum(items) / len(items) if items else 0.0


def _normalise_probabilities(value: Mapping[str, float]) -> dict[str, float]:
    cleaned = {str(key): max(0.0, float(score)) for key, score in value.items()}
    total = sum(cleaned.values())
    if total <= 0.0:
        return {key: 0.0 for key in cleaned}
    return {key: score / total for key, score in cleaned.items()}


def route_captionless_visual_scores_v7(
    *,
    clip_scores: Mapping[str, float],
    nsfw_scores: Mapping[str, float],
    per_frame_labels: Sequence[str],
    config: VisualEvidenceV7Config | None = None,
) -> dict[str, Any]:
    """Turn fixed-model scores into a non-authoritative evidence label.

    This function never produces moderation actions, age conclusions, child
    labels, or verified provenance. Those remain the responsibility of the V6
    deterministic policy layer after independent validation.
    """

    cfg = config or VisualEvidenceV7Config()
    clip = _normalise_probabilities(clip_scores)
    nsfw = _normalise_probabilities(nsfw_scores)
    art = clip.get("verified_art_culture_or_education", 0.0)
    intimacy = clip.get("non_explicit_intimacy", 0.0)
    explicit = clip.get("explicit_adult_sexual_content", 0.0)
    safe = clip.get("safe_or_other", 0.0)
    high = nsfw.get("high", 0.0)
    medium = nsfw.get("medium", 0.0)
    low = nsfw.get("low", 0.0)
    neutral = nsfw.get("neutral", 0.0)
    sexual_risk = min(1.0, medium + high)

    candidate = "uncertain"
    confidence = 0.0
    reason = "scores_below_locked_development_thresholds"

    art_candidate = bool(
        art >= cfg.art_minimum
        and art >= explicit + cfg.art_margin_over_explicit
        and art >= max(intimacy, safe)
    )
    explicit_candidate = bool(
        (
            explicit >= cfg.explicit_clip_minimum
            and explicit >= intimacy
            and sexual_risk >= cfg.explicit_sexual_risk_minimum
        )
        or high >= cfg.explicit_high_override
        or (
            medium >= cfg.explicit_medium_override
            and sexual_risk >= cfg.explicit_medium_override_risk
        )
    )
    intimacy_candidate = bool(
        intimacy >= cfg.intimacy_minimum
        and intimacy >= explicit + cfg.intimacy_margin
        and high < cfg.explicit_high_override
        and medium <= cfg.intimacy_medium_maximum
    )
    safe_candidate = bool(
        safe >= cfg.safe_minimum and neutral >= max(high, medium + low)
    )

    if art_candidate:
        candidate = "verified_art_culture_or_education"
        confidence = min(1.0, 0.72 * art + 0.28 * max(neutral, low))
        reason = "fixed_clip_art_context_candidate"
    elif explicit_candidate:
        candidate = "explicit_adult_sexual_content"
        confidence = min(
            1.0,
            0.55 * sexual_risk + 0.45 * max(explicit, high, medium),
        )
        reason = "medium_high_sexual_risk_and_fixed_context_consensus"
    elif intimacy_candidate:
        candidate = "non_explicit_intimacy"
        confidence = min(1.0, 0.70 * intimacy + 0.30 * (neutral + low))
        reason = "fixed_clip_non_explicit_intimacy_candidate"
    elif safe_candidate:
        candidate = "safe_or_other"
        confidence = min(1.0, 0.65 * safe + 0.35 * neutral)
        reason = "safe_context_and_neutral_consensus"

    frame_consensus = 0.0
    if per_frame_labels and candidate != "uncertain":
        frame_consensus = sum(label == candidate for label in per_frame_labels) / len(
            per_frame_labels
        )
        # Explicit animated content is evaluated from the aggregate evidence.
        # Requiring a majority of sampled frames to independently cross every
        # threshold would miss short explicit segments. The aggregate is an
        # arithmetic mean, so one isolated frame cannot dominate it.
        if (
            candidate != "explicit_adult_sexual_content"
            and frame_consensus < cfg.frame_consensus_minimum
        ):
            candidate = "uncertain"
            confidence = min(confidence, frame_consensus)
            reason = "insufficient_frame_consensus"

    # A zero-shot score should not be interpreted as a calibrated probability.
    # The conservative confidence floor makes low-separation outputs abstain.
    top_scores = sorted(clip.values(), reverse=True)
    clip_margin = top_scores[0] - top_scores[1] if len(top_scores) > 1 else 0.0
    if candidate != "uncertain" and confidence < cfg.decision_minimum:
        candidate = "uncertain"
        reason = "combined_confidence_below_threshold"

    return {
        "available": True,
        "candidate_boundary": candidate,
        "candidate_confidence": round(confidence, 6),
        "reason": reason,
        "clip_group_scores": {key: round(score, 6) for key, score in clip.items()},
        "clip_margin": round(clip_margin, 6),
        "nsfw_level_scores": {key: round(score, 6) for key, score in nsfw.items()},
        "frame_consensus": round(frame_consensus, 6),
        "sexual_risk_score": round(sexual_risk, 6),
        "policy_revision": "v7-development-v2-medium-high-risk",
        "moderation_action": None,
        "art_context_verified": False,
        "adult_age_verified": False,
        "child_age_inference_performed": False,
        "automatic_allow_allowed": False,
        "automatic_enforcement_allowed": False,
        "connected_to_live_moderation": False,
        "independently_validated": False,
        "development_candidate_only": True,
    }


def _sample_frame_indexes(frame_count: int, maximum: int) -> list[int]:
    if frame_count <= 1:
        return [0]
    sample_count = min(frame_count, maximum)
    if sample_count == 1:
        return [0]
    return sorted(
        {
            int(round(index * (frame_count - 1) / (sample_count - 1)))
            for index in range(sample_count)
        }
    )


def load_visual_frames(path: Path, *, max_frames: int) -> list[Any]:
    from PIL import Image

    suffix = path.suffix.lower()
    if suffix not in {".jpg", ".jpeg", ".png", ".webp", ".bmp", ".gif"}:
        raise ValueError(
            "V7 development supports still images and animated GIF files only."
        )
    frames: list[Any] = []
    with Image.open(path) as image:
        frame_count = int(getattr(image, "n_frames", 1))
        for index in _sample_frame_indexes(frame_count, max_frames):
            image.seek(index)
            frames.append(image.convert("RGB").copy())
    if not frames:
        raise RuntimeError("No decodable visual frame was found.")
    return frames


class CaptionlessVisualEvidenceV7:
    def __init__(
        self,
        *,
        config: VisualEvidenceV7Config | None = None,
        local_files_only: bool = False,
    ) -> None:
        self.config = config or VisualEvidenceV7Config()
        self.local_files_only = local_files_only
        self._loaded = False
        self._torch: Any = None
        self._device = "cpu"
        self._nsfw_processor: Any = None
        self._nsfw_model: Any = None
        self._clip_processor: Any = None
        self._clip_model: Any = None
        self._resolved_revisions: dict[str, str] = {}

    @property
    def resolved_revisions(self) -> Mapping[str, str]:
        return dict(self._resolved_revisions)

    def _load(self) -> None:
        if self._loaded:
            return
        import torch
        from transformers import (
            AutoImageProcessor,
            AutoModelForImageClassification,
            CLIPModel,
            CLIPProcessor,
        )

        self._torch = torch
        self._device = "cuda" if torch.cuda.is_available() else "cpu"
        self._nsfw_processor = AutoImageProcessor.from_pretrained(
            FREEPIK_MODEL_ID,
            revision=FREEPIK_MODEL_REVISION,
            local_files_only=self.local_files_only,
        )
        self._nsfw_model = AutoModelForImageClassification.from_pretrained(
            FREEPIK_MODEL_ID,
            revision=FREEPIK_MODEL_REVISION,
            local_files_only=self.local_files_only,
            use_safetensors=True,
        ).to(self._device)
        self._clip_processor = CLIPProcessor.from_pretrained(
            CLIP_MODEL_ID,
            revision=CLIP_MODEL_REVISION,
            local_files_only=self.local_files_only,
        )
        self._clip_model = CLIPModel.from_pretrained(
            CLIP_MODEL_ID,
            revision=CLIP_MODEL_REVISION,
            local_files_only=self.local_files_only,
            use_safetensors=True,
        ).to(self._device)
        self._nsfw_model.eval()
        self._clip_model.eval()
        self._resolved_revisions = {
            FREEPIK_MODEL_ID: str(
                getattr(self._nsfw_model.config, "_commit_hash", "")
                or FREEPIK_MODEL_REVISION
            ),
            CLIP_MODEL_ID: str(
                getattr(self._clip_model.config, "_commit_hash", "")
                or CLIP_MODEL_REVISION
            ),
        }
        self._loaded = True

    @staticmethod
    def _label_name(value: Any) -> str:
        label = str(value).strip().lower().replace("label_", "")
        aliases = {
            "0": "neutral",
            "1": "low",
            "2": "medium",
            "3": "high",
            "sfw": "neutral",
            "safe": "neutral",
            "nsfw": "high",
        }
        return aliases.get(label, label)

    def _nsfw_scores(self, frames: Sequence[Any]) -> tuple[dict[str, float], list[dict[str, float]]]:
        torch = self._torch
        inputs = self._nsfw_processor(images=list(frames), return_tensors="pt")
        inputs = {key: value.to(self._device) for key, value in inputs.items()}
        with torch.inference_mode():
            probabilities = self._nsfw_model(**inputs).logits.softmax(dim=-1).cpu()
        id2label = dict(getattr(self._nsfw_model.config, "id2label", {}))
        per_frame: list[dict[str, float]] = []
        for row in probabilities:
            item = {"neutral": 0.0, "low": 0.0, "medium": 0.0, "high": 0.0}
            for index, score in enumerate(row.tolist()):
                label = self._label_name(
                    id2label.get(index, id2label.get(str(index), index))
                )
                if label in item:
                    item[label] += float(score)
            per_frame.append(_normalise_probabilities(item))
        aggregate = {
            label: _mean(frame.get(label, 0.0) for frame in per_frame)
            for label in ("neutral", "low", "medium", "high")
        }
        return _normalise_probabilities(aggregate), per_frame

    def _clip_scores(self, frames: Sequence[Any]) -> tuple[dict[str, float], list[dict[str, float]]]:
        torch = self._torch
        prompts: list[str] = []
        prompt_groups: list[str] = []
        for group, variants in PROMPT_GROUPS.items():
            prompts.extend(variants)
            prompt_groups.extend([group] * len(variants))
        inputs = self._clip_processor(
            text=prompts,
            images=list(frames),
            return_tensors="pt",
            padding=True,
        )
        inputs = {key: value.to(self._device) for key, value in inputs.items()}
        with torch.inference_mode():
            probabilities = self._clip_model(**inputs).logits_per_image.softmax(dim=-1).cpu()
        per_frame: list[dict[str, float]] = []
        for row in probabilities:
            item = {group: 0.0 for group in PROMPT_GROUPS}
            for group, score in zip(prompt_groups, row.tolist(), strict=True):
                item[group] += float(score)
            per_frame.append(_normalise_probabilities(item))
        aggregate = {
            group: _mean(frame.get(group, 0.0) for frame in per_frame)
            for group in PROMPT_GROUPS
        }
        return _normalise_probabilities(aggregate), per_frame

    def analyze_path(self, path: str | Path) -> dict[str, Any]:
        visual_path = Path(path).expanduser().resolve()
        if not visual_path.is_file():
            raise FileNotFoundError(f"Visual file does not exist: {visual_path}")
        self._load()
        frames = load_visual_frames(visual_path, max_frames=self.config.max_frames)
        nsfw_scores, per_frame_nsfw = self._nsfw_scores(frames)
        clip_scores, per_frame_clip = self._clip_scores(frames)

        per_frame_labels: list[str] = []
        for clip, nsfw in zip(per_frame_clip, per_frame_nsfw, strict=True):
            frame_result = route_captionless_visual_scores_v7(
                clip_scores=clip,
                nsfw_scores=nsfw,
                per_frame_labels=(),
                config=self.config,
            )
            per_frame_labels.append(str(frame_result["candidate_boundary"]))
        result = route_captionless_visual_scores_v7(
            clip_scores=clip_scores,
            nsfw_scores=nsfw_scores,
            per_frame_labels=per_frame_labels,
            config=self.config,
        )
        per_frame_label_counts = {
            label: per_frame_labels.count(label)
            for label in sorted(set(per_frame_labels))
        }
        return {
            **result,
            "frames_evaluated": len(frames),
            "per_frame_label_counts": per_frame_label_counts,
            "device": self._device,
            "model_ids": [FREEPIK_MODEL_ID, CLIP_MODEL_ID],
            "resolved_revisions": dict(self._resolved_revisions),
            "raw_media_stored": False,
            "raw_model_embeddings_stored": False,
            "free_form_model_output_used": False,
            "local_llm_used": False,
        }


_DEFAULT_ANALYZER: CaptionlessVisualEvidenceV7 | None = None


def analyze_captionless_visual_evidence_v7(
    path: str | Path, *, local_files_only: bool = False
) -> dict[str, Any]:
    global _DEFAULT_ANALYZER
    if _DEFAULT_ANALYZER is None or _DEFAULT_ANALYZER.local_files_only != local_files_only:
        _DEFAULT_ANALYZER = CaptionlessVisualEvidenceV7(
            local_files_only=local_files_only
        )
    return _DEFAULT_ANALYZER.analyze_path(path)
