from io import BytesIO
from pathlib import Path

from PIL import Image, UnidentifiedImageError

from app.services.ocr_service import (
    OCRProcessingError,
    extract_text_from_pil_image,
)
from app.services.visual_service import (
    VisualProcessingError,
    describe_pil_image,
)


SUPPORTED_IMAGE_EXTENSIONS = {
    ".jpg",
    ".jpeg",
    ".png",
    ".webp",
}


class ImageProcessingError(Exception):
    pass


def process_image(
    file_name: str,
    file_bytes: bytes,
) -> dict:
    extension = Path(file_name).suffix.lower()

    if extension not in SUPPORTED_IMAGE_EXTENSIONS:
        raise ImageProcessingError(
            f"Unsupported image type: {extension}"
        )

    warnings: list[str] = []
    ocr_text = ""
    visual_description = ""

    try:
        with Image.open(
            BytesIO(file_bytes)
        ) as image:
            image.load()

            metadata = {
                "width": image.width,
                "height": image.height,
                "format": image.format,
                "color_mode": image.mode,
                "animated": bool(
                    getattr(
                        image,
                        "is_animated",
                        False,
                    )
                ),
                "frame_count": int(
                    getattr(
                        image,
                        "n_frames",
                        1,
                    )
                ),
            }

            try:
                ocr_text = (
                    extract_text_from_pil_image(
                        image
                    )
                )

            except OCRProcessingError as exc:
                warnings.append(
                    f"OCR warning: {exc}"
                )

            try:
                visual_description = (
                    describe_pil_image(image)
                )

            except VisualProcessingError as exc:
                warnings.append(
                    "Visual-description warning: "
                    f"{exc}"
                )

    except (
        UnidentifiedImageError,
        OSError,
        ValueError,
        Image.DecompressionBombError,
    ) as exc:
        raise ImageProcessingError(
            "The uploaded image is invalid, "
            "damaged, or unsafe to open."
        ) from exc

    if not ocr_text:
        warnings.append(
            "No readable English text was detected "
            "in the image."
        )

    if not visual_description:
        warnings.append(
            "No visual description was generated."
        )

    warnings.append(
        "The visual description is generated by a "
        "general captioning model and may be incomplete."
    )

    return {
        "visual_description": visual_description,
        "ocr_text": ocr_text,
        "metadata": metadata,
        "warnings": warnings,
    }